local defs = {
	{
		name = "coin",
		radius = 48,
		money = 50,
		col = {1, 0.8, 0, 1},
		image = "coin",
	},
	{
		name = "bigCoin",
		radius = 65,
		money = 200,
		col = {1, 0.8, 0, 1},
		image = "gem_1",
	},
	{
		name = "chest",
		radius = 75,
		money = 500,
		col = {1, 0.8, 0, 1},
		image = "treasure_chest_small",
	},
	{
		name = "bigChest",
		radius = 90,
		money = 5000,
		col = {1, 0.8, 0, 1},
		toolSkip = true,
		image = "treasure_chest",
	},
	{
		name = "portal_1",
		radius = 120,
		portalExit = 1,
		alpha = 0.95,
		col = {0.9, 0.2, 1, 1},
		toolSkip = true,
		image = "portal_furled",
		rotSpeed = 0.3,
	},
	{
		name = "portal_1_entrance",
		radius = 120,
		portalEntrance = 1,
		alpha = 0.8,
		col = {0.9, 0.2, 1, 1},
		toolSkip = true,
		image = "portal_unfurled",
		rotSpeed = 0.7,
	},
	{
		name = "portal_2",
		radius = 120,
		portalExit = 2,
		alpha = 0.95,
		col = {0.9, 0.2, 1, 1},
		toolSkip = true,
		image = "portal_furled",
		rotSpeed = 0.3,
	},
	{
		name = "portal_2_entrance",
		radius = 120,
		portalEntrance = 2,
		alpha = 0.8,
		col = {0.9, 0.2, 1, 1},
		toolSkip = true,
		image = "portal_unfurled",
		rotSpeed = 0.7,
	},
	{
		name = "start_portal",
		radius = 120,
		portalEntrance = "start",
		alpha = 0.8,
		col = {0.9, 0.2, 1, 1},
		toolSkip = true,
		image = "portal_unfurled",
		rotSpeed = 0.7,
	},
	{
		name = "ultraCoin",
		radius = 450,
		money = 20000,
		col = {1, 0.8, 0, 1},
		toolSkip = true,
	},
}

return defs
